# .choreo/component-config.yaml

component:
  name: flask-app
  version: 1.0.0
  description: A Flask application running in Docker

settings:
  port: 5000
  # Add other configuration settings as needed

dependencies:
  - flask
  - gunicorn
  # List other dependencies if needed
